<a href="https://colab.research.google.com/github/gprimo/information-retrieval/blob/main/src/trabalho3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [35]:
import xml.sax as sax

class QueryNumberHandler(sax.ContentHandler) :

  def startElement(self, name, attrs) :
    self.current = name

  def characters(self, content) :
    if self.current == "QueryNumber":
      self.QueryNumber = content


  def endElement(self, name) :
    if self.current == "QueryNumber":
      querynumberlist.append(self.QueryNumber)
    self.current = ""

In [36]:
import xml.sax as sax

class QueryTextHandler(sax.ContentHandler) :

  def startElement(self, name, attrs) :
    self.current = name

  def characters(self, content) :
    if self.current == "QueryText":
      self.QueryText = content


  def endElement(self, name) :
    if self.current == "QueryText":
      queryTextlist.append(self.QueryText)

    self.current = ""

In [71]:
import xml.etree.ElementTree as ET


f = open("/content/drive/MyDrive/Colab Notebooks/Data/PC.CFG", "r")
cfg = f.readlines()

#query.xml esta aqui em read
r = cfg[0].split('= ',1)[1]
read = r.split('\n', 1)[0]

#aqui é a diretiva pra criar o primeiro csv
q = cfg[1].split('= ',1)[1]
query = q.split('\n', 1)[0]


#aqui é a diretiva pra criar o segundo csv
d = cfg[2].split('= ',1)[1]
finalDocument = d.split('\n', 1)[0]
print(finalDocument)


g = open(read, 'r')
queryCreate = open(query, 'w+')
voteDocumentCreate = open(finalDocument, 'w+')
querynumberlist = []
queryTextlist = []
queryItemlist = []
document = []
queryNumber = []
vote = []

handler = QueryNumberHandler()
parser = sax.make_parser()
parser.setContentHandler(handler)
parser.parse(read)

handlerText = QueryTextHandler()
parserText = sax.make_parser()
parserText.setContentHandler(handlerText)
parserText.parse(read)

tree = ET.parse(read)
root = tree.getroot()
queryDocumentVotes = {}
votes = 0
iter = 1
docuIndex = '1'

for child in root:
  for item in child:
    if (item.tag == 'QueryNumber'):
      queryDocumentVotes[item.text] = [votes, []]
  

for child in root:
  for item in child:
    if (item.tag == 'QueryNumber'):
      query = item.text
    if (item.tag == 'Records'):
      for x in item: 
        sc = x.attrib['score']
        for key in queryDocumentVotes:
          if (int(key) == int(sc)):
            queryDocumentVotes[key][1].append(docuIndex)
            queryDocumentVotes[key] = [queryDocumentVotes[key][0] + 1, queryDocumentVotes[key][1]]
  iter = iter + 1
  docuIndex = str(iter)

i = 0
for item in querynumberlist:
  queryCreate.write(item + ';' + queryTextlist[i] + '\n')
  i = i + 1


for key in queryDocumentVotes:
  j = 0
  for item in queryDocumentVotes[key][1]:
    voteDocumentCreate.write(key + ';' + item + ';' + str(queryDocumentVotes[key][0]) + '\n')
    j = j + 1
  


/content/drive/MyDrive/Colab Notebooks/Data/queryout.csv


In [76]:
import xml.etree.ElementTree as ET

def BaseConvertXML(xml, base) :

  tree = ET.parse(xml)
  root = tree.getroot()

  tree = ET.parse(xml)
  root = tree.getroot()

  for record in root.iter('ABSTRACT'):
    base.append(record.text)
  

In [77]:
f = open("/content/drive/MyDrive/Colab Notebooks/Data/GLI.CFG", "r")
cfg = f.readlines()

#primeiro xml esta aqui em read
r = cfg[0].split('= ',1)[1]
read1 = r.split('\n', 1)[0]

#segunda xml esta aqui em read2
r = cfg[1].split('= ',1)[1]
read2 = r.split('\n', 1)[0]

#terceiro xml esta aqui em read3
r = cfg[2].split('= ',1)[1]
read3 = r.split('\n', 1)[0]

#quarto xml esta aqui em read4
r = cfg[3].split('= ',1)[1]
read4 = r.split('\n', 1)[0]

#quinto xml esta aqui em read5
r = cfg[4].split('= ',1)[1]
read5 = r.split('\n', 1)[0]

#sexto xml esta aqui em read6
r = cfg[5].split('= ',1)[1]
read6 = r.split('\n', 1)[0]

#aqui é a diretiva pra criar a lista invertida
d = cfg[6].split('= ',1)[1]
inverse = d.split('\n', 1)[0]

g = open(read, 'r')
queryCreate = open(inverse, 'w+')
print(inverse)

base1 = []
base1opt = []
base2 = []
base2opt = []
base3 = []
base3opt = []
base4 = []
base4opt = []
base5 = []
base5opt = []
base6 = []
base6opt = []
BaseConvertXML(read1, base1)
BaseConvertXML(read2, base2)
BaseConvertXML(read3, base3)
BaseConvertXML(read4, base4)
BaseConvertXML(read5, base5)
BaseConvertXML(read6, base6)

lista_invertida = {}
lista_invertida2 = {}
lista_invertida3 = {}
lista_invertida4 = {}
lista_invertida5 = {}
lista_invertida6 = {}

dataset = []


for word in base1:
  wordopt = word.replace(",","")
  wordopt = word.replace("\n"," ")
  base1opt.append(wordopt)
  dataset.append(wordopt)


for word in base2:
  wordopt2 = word.replace(",","")
  wordopt2 = word.replace("\n"," ")
  base2opt.append(wordopt2)
  dataset.append(wordopt2)

for word in base3:
  wordopt3 = word.replace(",","")
  wordopt3 = word.replace("\n"," ")
  base3opt.append(wordopt3)
  dataset.append(wordopt3)

for word in base4:
  wordopt4 = word.replace(",","")
  wordopt4 = word.replace("\n"," ")
  base4opt.append(wordopt4)
  dataset.append(wordopt4)

for word in base5:
  wordopt5 = word.replace(",","")
  wordopt5 = word.replace("\n"," ")
  base5opt.append(wordopt5)
  dataset.append(wordopt5)

for word in base6:
  wordopt6 = word.replace(",","")
  wordopt6 = word.replace("\n"," ")
  base6opt.append(wordopt6)
  dataset.append(wordopt6)


for i in range(len(base1opt)):
  fraselc = str.upper(base1opt[i]).split ()
  for palavra in fraselc:
    docs = lista_invertida.get(palavra, set())
    docs.add(i+1)
    lista_invertida[palavra] = docs

for i in range(len(base2opt)):
  fraselc = str.upper(base2opt[i]).split ()
  for palavra in fraselc:
    docs = lista_invertida2.get(palavra, set())
    docs.add(i+1)
    lista_invertida2[palavra] = docs

for i in range(len(base3opt)):
  fraselc = str.upper(base3opt[i]).split ()
  for palavra in fraselc:
    docs = lista_invertida3.get(palavra, set())
    docs.add(i+1)
    lista_invertida3[palavra] = docs

for i in range(len(base4opt)):
  fraselc = str.upper(base4opt[i]).split ()
  for palavra in fraselc:
    docs = lista_invertida4.get(palavra, set())
    docs.add(i+1)
    lista_invertida4[palavra] = docs

for i in range(len(base5opt)):
  fraselc = str.upper(base5opt[i]).split ()
  for palavra in fraselc:
    docs = lista_invertida5.get(palavra, set())
    docs.add(i+1)
    lista_invertida5[palavra] = docs

for i in range(len(base6opt)):
  fraselc = str.upper(base6opt[i]).split ()
  for palavra in fraselc:
    docs = lista_invertida6.get(palavra, set())
    docs.add(i+1)
    lista_invertida6[palavra] = docs


chaves = ["FIBROSIS","BLOOD","CHILDREN","CYSTIC","DESCRIBED","DETERMINED","DIAGNOSIS","HUMAN","INFECTION","LEVELS","METHOD","PSEUDOMONAS","RESPIRATORY", "CHILD" ,"SERUM", "SALIVA", "ACID"]
chaves.sort()
for i in chaves:
  queryCreate.write(i + ";" + str(len(lista_invertida[i])) + ';' + str(len(lista_invertida2[i])) + ';'+ str(len(lista_invertida3[i])) +';'+ str(len(lista_invertida4[i])) + ';'+ str(len(lista_invertida5[i])) + ';' + str(len(lista_invertida6[i])) + '\n')
  #queryCreate.write(i + ";" + len(lista_invertida[i])) +  len(lista_invertida2[i]), len(lista_invertida3[i]), len(lista_invertida4[i]), len(lista_invertida5[i]), len(lista_invertida6[i]) )




/content/drive/MyDrive/Colab Notebooks/Data/listainvertida.csv


In [78]:
import csv

f = open("/content/drive/MyDrive/Colab Notebooks/Data/INDEX.CFG", "r")
cfg = f.readlines()
listainvertida = {}

#primeiro xml esta aqui em read
r = cfg[0].split('= ',1)[1]
read = r.split('\n', 1)[0]


with open (read,"r") as file:
  file_csv = csv.reader(file, delimiter=";")
  for i, line in enumerate(file_csv):
    print(line)
    listainvertida[line[0]]=int(line[1])+int(line[2])+int(line[3])+int(line[4])+int(line[5])+int(line[6])


['ACID', '10', '3', '14', '11', '10', '20']
['BLOOD', '8', '13', '12', '7', '7', '9']
['CHILD', '3', '5', '6', '6', '4', '3']
['CHILDREN', '29', '28', '30', '30', '23', '31']
['CYSTIC', '83', '102', '131', '123', '120', '134']
['DESCRIBED', '6', '7', '5', '4', '4', '7']
['DETERMINED', '7', '6', '5', '5', '9', '6']
['DIAGNOSIS', '8', '11', '9', '15', '15', '6']
['FIBROSIS', '73', '89', '123', '108', '105', '118']
['HUMAN', '8', '5', '15', '14', '9', '12']
['INFECTION', '7', '6', '6', '10', '5', '6']
['LEVELS', '16', '16', '21', '6', '13', '19']
['METHOD', '14', '5', '7', '17', '10', '6']
['PSEUDOMONAS', '15', '8', '9', '5', '9', '14']
['RESPIRATORY', '13', '10', '10', '10', '10', '8']
['SALIVA', '5', '5', '12', '4', '3', '1']
['SERUM', '14', '28', '26', '23', '20', '32']


In [79]:
# biblioteca para ordenação
import heapq
print(listainvertida)

# ordena a lista para saber qual é a palavra que mais se repete
freq_words = heapq.nlargest(50,listainvertida, key=listainvertida.get)
print(freq_words)


{'ACID': 68, 'BLOOD': 56, 'CHILD': 27, 'CHILDREN': 171, 'CYSTIC': 693, 'DESCRIBED': 33, 'DETERMINED': 38, 'DIAGNOSIS': 64, 'FIBROSIS': 616, 'HUMAN': 63, 'INFECTION': 40, 'LEVELS': 91, 'METHOD': 59, 'PSEUDOMONAS': 60, 'RESPIRATORY': 61, 'SALIVA': 30, 'SERUM': 143}
['CYSTIC', 'FIBROSIS', 'CHILDREN', 'SERUM', 'LEVELS', 'ACID', 'DIAGNOSIS', 'HUMAN', 'RESPIRATORY', 'PSEUDOMONAS', 'METHOD', 'BLOOD', 'INFECTION', 'DETERMINED', 'DESCRIBED', 'SALIVA', 'CHILD']


In [80]:
  base1optupper = []
  base2optupper = []
  base3optupper = []
  base4optupper = []
  base5optupper = []
  base6optupper = []

  for data in base1opt:
    base1optupper.append(data.upper())

  for data in base2opt:
    base2optupper.append(data.upper())

  for data in base3opt:
    base3optupper.append(data.upper())

  for data in base4opt:
    base4optupper.append(data.upper())

  for data in base5opt:
    base5optupper.append(data.upper())

  for data in base6opt:
    base6optupper.append(data.upper())

In [81]:
# criando o IDF
import numpy as np 
import nltk
import re
import string
nltk.download('punkt')

def idf_create(query):

  word_idfs = {}
  for word in query:
      doc_count = 0 
      for data in base1optupper:
          if word in nltk.word_tokenize(data):
              doc_count += 1  
      for data in base2optupper:
        if word in nltk.word_tokenize(data):
            doc_count += 1    
      for data in base3optupper:
        if word in nltk.word_tokenize(data):
            doc_count += 1  
      for data in base4optupper:
        if word in nltk.word_tokenize(data):
            doc_count += 1   
      for data in base5optupper:
        if word in nltk.word_tokenize(data):
            doc_count += 1 
      for data in base6optupper:
        if word in nltk.word_tokenize(data):
            doc_count += 1             
      word_idfs[word] = np.log((6/doc_count)+1) 
  return word_idfs   

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [82]:
idf = idf_create(freq_words)
print(idf)


{'CYSTIC': 0.008583743691391435, 'FIBROSIS': 0.008571481050140963, 'CHILDREN': 0.030930300691358558, 'SERUM': 0.040005334613699206, 'LEVELS': 0.05770831762064677, 'ACID': 0.0750351859429141, 'DIAGNOSIS': 0.07796154146971192, 'HUMAN': 0.09097177820572679, 'RESPIRATORY': 0.09237332013101507, 'PSEUDOMONAS': 0.09531017980432493, 'METHOD': 0.08223809823697201, 'BLOOD': 0.09531017980432493, 'INFECTION': 0.10724553035359759, 'DETERMINED': 0.11551288712184424, 'DESCRIBED': 0.11778303565638346, 'SALIVA': 0.1582240052148942, 'CHILD': 0.17185025692665923}


In [83]:
def tf_create(query):

  tf_matrix = {}

  for word in query:
    doc_tf = []
    for data in base1optupper:
      frequency = 0
      for w in nltk.word_tokenize(data):
          if w == word:
            frequency += 1
      tf_word = frequency/len(nltk.word_tokenize(data))
    doc_tf.append(tf_word)

    for data in base2optupper:
      frequency = 0
      for w in nltk.word_tokenize(data):
          if w == word:
            frequency += 1
      tf_word = frequency/len(nltk.word_tokenize(data))
    doc_tf.append(tf_word)
    for data in base3optupper:
      frequency = 0
      for w in nltk.word_tokenize(data):
          if w == word:
            frequency += 1
      tf_word = frequency/len(nltk.word_tokenize(data))
    doc_tf.append(tf_word)
    for data in base4optupper:
      frequency = 0
      for w in nltk.word_tokenize(data):
          if w == word:
            frequency += 1
      tf_word = frequency/len(nltk.word_tokenize(data))
    doc_tf.append(tf_word)
    for data in base5optupper:
      frequency = 0
      for w in nltk.word_tokenize(data):
          if w == word:
            frequency += 1
      tf_word = frequency/len(nltk.word_tokenize(data))
    doc_tf.append(tf_word)
    for data in base6optupper:
      frequency = 0
      for w in nltk.word_tokenize(data):
          if w == word:
            frequency += 1
      tf_word = frequency/len(nltk.word_tokenize(data))
    doc_tf.append(tf_word)

    tf_matrix[word] = doc_tf
  
  return tf_matrix  



In [84]:
matrix = tf_create(freq_words)
print(matrix)


{'CYSTIC': [0.015384615384615385, 0.005813953488372093, 0.0, 0.05555555555555555, 0.0, 0.02040816326530612], 'FIBROSIS': [0.015384615384615385, 0.005813953488372093, 0.0, 0.05555555555555555, 0.0, 0.02040816326530612], 'CHILDREN': [0.0, 0.011627906976744186, 0.030303030303030304, 0.0, 0.006666666666666667, 0.006802721088435374], 'SERUM': [0.0, 0.029069767441860465, 0.0, 0.0, 0.0, 0.027210884353741496], 'LEVELS': [0.0, 0.0, 0.0, 0.0, 0.0, 0.02040816326530612], 'ACID': [0.0, 0.0, 0.0, 0.0, 0.0, 0.02040816326530612], 'DIAGNOSIS': [0.0, 0.005813953488372093, 0.030303030303030304, 0.0, 0.0, 0.0], 'HUMAN': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'RESPIRATORY': [0.0, 0.0, 0.0, 0.0, 0.02, 0.0], 'PSEUDOMONAS': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'METHOD': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'BLOOD': [0.015384615384615385, 0.0, 0.0, 0.0, 0.0, 0.0], 'INFECTION': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'DETERMINED': [0.0, 0.005813953488372093, 0.0, 0.0, 0.0, 0.0], 'DESCRIBED': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'SALIVA': [0

In [85]:
# TF-IDF cálculo
import numpy as np 

def tfidf_create(tfmatrix, idfarray):
  tfidf_matrix = []

  for word in tfmatrix.keys():
      tfidf = []
      for value in tfmatrix[word]:
          score = value * idfarray[word]
          tfidf.append(score)
      tfidf_matrix.append(tfidf)
  
  np.set_printoptions(suppress=True)
  arr = np.array(tfidf_matrix)

  return arr


In [86]:
tfidfmatrix = tfidf_create(matrix, idf)
print(tfidfmatrix)


[[0.00013206 0.00004991 0.         0.00047687 0.         0.00017518]
 [0.00013187 0.00004983 0.         0.00047619 0.         0.00017493]
 [0.         0.00035965 0.00093728 0.         0.0002062  0.00021041]
 [0.         0.00116295 0.         0.         0.         0.00108858]
 [0.         0.         0.         0.         0.         0.00117772]
 [0.         0.         0.         0.         0.         0.00153133]
 [0.         0.00045326 0.00236247 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.00184747 0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.00146631 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.00067159 0.         0.         0.         0.        ]
 [0.         0.         0.        

In [90]:
import csv

f = open("/content/drive/MyDrive/Colab Notebooks/Data/BUSCAR.CFG", "r")
cfg = f.readlines()

r = cfg[0].split('= ',1)[1]
query = r.split('\n', 1)[0]

r = cfg[1].split('= ',1)[1]
busca = r.split('\n', 1)[0]

g = open(query, 'r')
queryCreate = open(busca, 'w+')
queries = {}
queryTerms = []
queryTermstokenize = []
finalTermsQuery = []
queriesUpper = []


with open (query,"r") as file:
  file_csv = csv.reader(file, delimiter=";")
  for i, line in enumerate(file_csv):
    queries[line[0]] = line[1]

for key, value in queries.items() :
  queryTerms.append(value)

for word in queryTerms:
  tokenTerm = nltk.word_tokenize(word)
  queryTermstokenize.append(tokenTerm)

for term in queryTermstokenize:
  for x in term:
    if len(x) > 3:
      finalTermsQuery.append(x)

for word in finalTermsQuery:
  upperTerm = str.upper(word)
  queriesUpper.append(upperTerm)

queriesUpper.sort()
print(queriesUpper)




['AERUGINOSA', 'ALBUMIN', 'ANTIMICROBIAL', 'EOSINOPHILIA', 'HETEROZYGOUS', 'HOMOZYGOUS', 'INFECTION', 'MECONIUM', 'NASAL', 'PERIPHERAL', 'PSEUDOMONAS', 'SHWACHMAN-KULCZYCKI', 'THERAPY']


In [115]:
reverselist = {}
queriesUpper.sort()



for item in queriesUpper:
  if lista_invertida[item] == 0:
    reverselist[item] = 0
  else:
    reverselist[item] = len(lista_invertida[item])


print(reverselist)

freqwords = heapq.nlargest(50,reverselist, key=reverselist.get)
print(freqwords)






{'AERUGINOSA': 9, 'ALBUMIN': 4, 'ANTIMICROBIAL': 0, 'EOSINOPHILIA': 0, 'HETEROZYGOUS': 0, 'HOMOZYGOUS': 1, 'INFECTION': 7, 'MECONIUM': 4, 'NASAL': 3, 'PERIPHERAL': 3, 'PSEUDOMONAS': 15, 'SHWACHMAN-KULCZYCKI': 0, 'THERAPY': 9}
['PSEUDOMONAS', 'AERUGINOSA', 'THERAPY', 'INFECTION', 'ALBUMIN', 'MECONIUM', 'NASAL', 'PERIPHERAL', 'HOMOZYGOUS', 'ANTIMICROBIAL', 'EOSINOPHILIA', 'HETEROZYGOUS', 'SHWACHMAN-KULCZYCKI']


In [116]:
idf = idf_create(freqwords)
print(idf)


{'PSEUDOMONAS': 0.09531017980432493, 'AERUGINOSA': 0.09381875521765491, 'THERAPY': 0.09237332013101507, 'INFECTION': 0.10724553035359759, 'ALBUMIN': 0.23180161405732438, 'MECONIUM': 0.1278333715098848, 'NASAL': 0.3566749439387324, 'PERIPHERAL': 0.4054651081081644, 'HOMOZYGOUS': 0.3566749439387324, 'ANTIMICROBIAL': 0.6931471805599453, 'EOSINOPHILIA': 1.0986122886681098, 'HETEROZYGOUS': 0.26236426446749106, 'SHWACHMAN-KULCZYCKI': 0.9162907318741551}


In [117]:
matrix = tf_create(freqwords)
print(matrix)


{'PSEUDOMONAS': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'AERUGINOSA': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'THERAPY': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'INFECTION': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'ALBUMIN': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'MECONIUM': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'NASAL': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'PERIPHERAL': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'HOMOZYGOUS': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'ANTIMICROBIAL': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'EOSINOPHILIA': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'HETEROZYGOUS': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'SHWACHMAN-KULCZYCKI': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
